spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
ftp:
  host: ${habeshait.ftp.host}
  password: ${habeshait.ftp.password}
  port: 21
  user: ${habeshait.ftp.user}
admin:
  username: ${admin.name}
  password: ${admin.pass}
user:
  username: ${user.name}
  password: ${user.pass}